"""
Chat session and message document models.

Design:
- Each chat session belongs to one user + one workflow
- Messages are embedded as an array within the session document
  (MongoDB's document model works well here — no joins needed)
- Each assistant message carries metadata: which agents ran,
  confidence score, cache hit, latency, SQL generated, etc.
- Conversation context is built from the last N messages
  (controlled by workflow.feature_flags.max_history_messages)
"""

from datetime import datetime, timezone
from enum import StrEnum
from typing import Any, Optional

from pydantic import BaseModel, Field


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


class MessageRole(StrEnum):
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class AgentTraceEntry(BaseModel):
    """
    Trace record for a single agent's execution within a response.
    Stored per-message for observability and debugging.
    """

    agent_type: str  # retrieval | web_search | guardrail
    status: str  # success | skipped | failed
    duration_ms: float = 0.0
    input_summary: str = ""
    output_summary: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)
    # e.g., {"tables_found": ["orders", "customers"], "sql_generated": "SELECT ..."}


class MessageMetadata(BaseModel):
    """Rich metadata attached to assistant messages."""

    agent_trace: list[AgentTraceEntry] = Field(default_factory=list)
    confidence_score: Optional[float] = None
    cached: bool = False
    cache_key: Optional[str] = None
    total_latency_ms: float = 0.0
    model_used: str = ""
    tokens_used: Optional[int] = None
    sql_query: Optional[str] = None  # The SQL generated by LlamaIndex
    tables_referenced: list[str] = Field(default_factory=list)
    error: Optional[str] = None


class ChatMessage(BaseModel):
    """Single message within a chat session."""

    role: MessageRole
    content: str
    metadata: Optional[MessageMetadata] = None
    timestamp: datetime = Field(default_factory=_utc_now)


class ChatSessionDocument(BaseModel):
    """
    MongoDB document for a chat session.

    Embedded messages pattern — efficient for:
    - Loading full conversation context in one read
    - Appending new messages with $push
    - Limiting context window with $slice

    For very long conversations (1000+ messages), consider
    splitting into a separate messages collection.
    """

    id: Optional[str] = Field(None, alias="_id")
    user_id: str
    workflow_id: str

    # Session metadata
    title: str = "New Chat"  # Auto-generated from first message
    is_active: bool = True

    # Embedded messages
    messages: list[ChatMessage] = Field(default_factory=list)
    message_count: int = 0

    # Audit
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)

    class Config:
        populate_by_name = True
        json_encoders = {datetime: lambda v: v.isoformat()}

    def get_context_messages(self, max_messages: int = 20) -> list[ChatMessage]:
        """
        Return the last N messages for building LLM context.
        Always includes the system message if present.
        """
        if not self.messages:
            return []

        # Keep system message + last N user/assistant messages
        system_msgs = [m for m in self.messages if m.role == MessageRole.SYSTEM]
        conv_msgs = [m for m in self.messages if m.role != MessageRole.SYSTEM]

        recent = conv_msgs[-max_messages:] if len(conv_msgs) > max_messages else conv_msgs
        return system_msgs + recent

    def to_llm_messages(self, max_messages: int = 20) -> list[dict[str, str]]:
        """
        Format conversation history for LLM API consumption.
        Returns list of {"role": "user"|"assistant", "content": "..."}.
        """
        context = self.get_context_messages(max_messages)
        return [
            {"role": msg.role.value, "content": msg.content}
            for msg in context
        ]

    def to_mongo(self) -> dict:
        data = self.model_dump(by_alias=False, exclude={"id"})
        data["updated_at"] = _utc_now()
        data["message_count"] = len(data.get("messages", []))
        return data